%YAML 1.2
---

data:
    db_dir: ./shuffled_fens/
    cp_dir: ./checkpoints/
    log_dir: ./logs/
    val_file: ./shuffled_0.data

train:
    lr: 0.0003
    grad_norm: 4.0
    val_size: 100000
    bs: 1024
    val_every: 500
    num_workers: 3
    optim: Adam # {SGD | Adam | RAdam}
    warmup_steps: 1000

model:
    filters: 32
    blocks: 4
    head: 32
    head_v2: true # {true | false}, if missing assumes 'false'
    head_filters: 1
    use_se: true # {true | false}, if missing assumes 'false'
    se_ratio: 8
    block_activation: Mish # {ReLU | Mish}
...
