%YAML 1.2
---

data:
    db_dir: ./shuffled_fens/
    cp_dir: ./checkpoints/
    log_dir: ./logs/
    val_dir: ./val/
    stats_v2: true

train:
    lr: 0.0003
    lr_min: 0.000003  # LR scheduler eta_min
    lr_steps: 1000000 # LR scheduler T_max
    grad_norm: 4.0
    val_size: 100000
    bs: 1024
    val_every: 500
    train_every: 100
    checkpoint_every: 500
    num_workers: 3
    optim: Adam # {SGD | Adam | RAdam}
    warmup_steps: 1000

model:
    filters: 32
    blocks: 4
    head: 32
    head_v2: true # {true | false}, if missing assumes 'false'
    head_filters: 1
    use_se: true # {true | false}, if missing assumes 'false'
    se_ratio: 8
    block_activation: Mish # {ReLU | Mish}
...
