%YAML 1.2
---

data:
    db_dir: ./shuffled_fens/
    cp_dir: ./checkpoints/
    log_dir: ./logs/
    test_file: ./shuffled_0.data

train:
    lr: 0.0003
    grad_norm: 4.0
    test_size: 100000
    bs: 1024
    test_every: 500
    num_workers: 3
    optim: Adam # {SGD | Adam}
    warmup_steps: 1000

model:
    filters: 32
    blocks: 4
    head: 32
    head_v2: true # {true | false}, if missing assumes 'false'
    use_se: true # {true | false}, if missing assumes 'false'
    se_ratio: 8
...
